### ISSUE TITLE
Não consigo executar?

### ISSUE THREAD

**Issue by tloriato** [jansenfelipe/cpf-gratis#13]
Primeiramente gostaria de pedir desculpas pela Issue tão fútil, mas sou obrigado a reconhecer minhta total inaptidão em relação à php. Esclarecido isso:

**Problema:** 
Não consigo reproduzir o captcha, a imagem vem sempre corrompida.
![untitled](https://cloud.githubusercontent.com/assets/11580564/22573514/767c4d58-e990-11e6-85ca-e3604a31e866.png)

**O que foi feito?**
_Ubuntu 14.04_
- Instalei o Apache e o PHP pelo terminal
- Naveguei até /var/www/html
- `$ composer require jansenfelipe/cpf-gratis`
- Criei um arquivo index.php com o seguinte contéudo:
```
<html>
 <head>
  <title>PHP Teste</title>
 </head>
 <body>
<?php
require_once '../vendor/autoload.php';
use JansenFelipe\CpfGratis\CpfGratis;
if(isset($_POST['captcha']) && isset($_POST['cookie']) && isset($_POST['cpf']) && isset($_POST['data_nascimento'])){
    $dados = CpfGratis::consulta($_POST['cpf'], $_POST['data_nascimento'], $_POST['captcha'], $_POST['cookie']);
    var_dump($dados);
    die;
}else
    $params = CpfGratis::getParams();
?>

<img src="<?php echo $params['captchaBase64'] ?>" />

<form method="POST">
    <input type="hidden" name="cookie" value="<?php echo $params['cookie'] ?>" />
    
    <input type="text" name="captcha" placeholder="Captcha" />
    <input type="text" name="cpf" placeholder="CPF" />
    <input type="text" name="data_nascimento" placeholder="Nascimento (DDMMYYYY)" />
    
    <button type="submit">Consultar</button>
</form>
 </body>
</html>
```
- Acessei o `localhost`

**Possíveis Causas:**
- Eu

Você poderia me ajudar? Obrigado!

**Comment by jansenfelipe** [comment]
Bom dia @tloriato ! Nenhuma mensagem de erro ou warning? Dá uma olhada nos logs, pois só com as informações que vc passou, não consigo te ajudar.

A lib retorna uma string base64 que representa a imagem. Verifique o conteúdo de `$params['captchaBase64']`

---
#### Observação:

Uma outra forma para vc testar a library (e mais fácil, sem apache)

Faça o clone do repositório em um diretório qualquer da sua máquina, acesse e execute um comando para iniciar o [servidor embutido no PHP](http://php.net/manual/en/features.commandline.webserver.php). 

Segue comandos:

```shell
$ git clone https://github.com/jansenfelipe/cpf-gratis.git
$ cd cpf-gratis
$ composer install
$ php -S localhost:8000 -t example
```

Done! 😄 

![screen shot 2017-02-03 at 09 43 05](https://cloud.githubusercontent.com/assets/3134214/22590074/adb0ed06-e9f4-11e6-8c6d-b7057aa96e5a.png)

**Comment by tloriato** [comment]
Tentei executar exatamente os passos listados aí, mas ocorre o erro listado a seguir.

**Chrome:**
_HTTP ERROR 500_

**Terminal:**

```
tloriato@tloriato-desktop:~/Documents/cpf-gratis$ php -S localhost:8000 -t example
PHP 7.0.13-0ubuntu0.16.04.1 Development Server started at Fri Feb  3 12:06:54 2017
Listening on http://localhost:8000
Document root is /home/tloriato/Documents/cpf-gratis/example
Press Ctrl-C to quit.
[Fri Feb  3 12:06:59 2017] PHP Warning:  require_once(../vendor/autoload.php): failed to open stream: No such file or directory in /home/tloriato/Documents/cpf-gratis/example/index.php on line 3
[Fri Feb  3 12:06:59 2017] PHP Fatal error:  require_once(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/tloriato/Documents/cpf-gratis/example/index.php on line 3
[Fri Feb  3 12:06:59 2017] 127.0.0.1:46050 [500]: / - require_once(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/tloriato/Documents/cpf-gratis/example/index.php on line 3

```

**Comment by jansenfelipe** [comment]
@tloriato esqueceu do `composer install`?

O erro que aparece está dizendo que não conseguiu achar o arquivo `autoload.php` ..

**Comment by tloriato** [comment]
@jansenfelipe Creio que havia executado, mas apaguei a pasta e tentei de novo e esse é o resultado ao executar `composer install`:

_**tloriato@tloriato-desktop:~/Documents/cpf-gratis$ composer install**_
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 4.8.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.9 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.8 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.7 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.6 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.5 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.4 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.34 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.33 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.32 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.31 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.30 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.29 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.28 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.27 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.26 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.25 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.24 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.23 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.22 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.21 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.20 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.19 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.18 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.17 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.16 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.15 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.14 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.13 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.12 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.11 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.10 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.8.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.7.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.7.7 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.7.6 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.7.5 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.7.4 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.7.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.7.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.7.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.7.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.9 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.8 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.7 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.6 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.5 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.4 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.10 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.6.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.5.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.5.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.5.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.4.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.4.5 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.4.4 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.4.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.4.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.4.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.4.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.3.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.3.5 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.3.4 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.3.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.3.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.3.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.3.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.2.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.2.6 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.2.5 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.2.4 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.2.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.2.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.2.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.2.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.1.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.1.6 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.1.5 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.1.4 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.1.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.1.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.1.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.1.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.9 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.8 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.7 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.6 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.5 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.4 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.20 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.19 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.18 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.17 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.16 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.15 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.14 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.13 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.12 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.11 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.10 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpunit/phpunit 4.0.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - Installation request for phpunit/phpunit ~4.0 -> satisfiable by phpunit/phpunit[4.0.0, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.x-dev, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.2.5, 4.2.6, 4.2.x-dev, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.3.4, 4.3.5, 4.3.x-dev, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.4.5, 4.4.x-dev, 4.5.0, 4.5.1, 4.5.x-dev, 4.6.0, 4.6.1, 4.6.10, 4.6.2, 4.6.3, 4.6.4, 4.6.5, 4.6.6, 4.6.7, 4.6.8, 4.6.9, 4.6.x-dev, 4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.7.4, 4.7.5, 4.7.6, 4.7.7, 4.7.x-dev, 4.8.0, 4.8.1, 4.8.10, 4.8.11, 4.8.12, 4.8.13, 4.8.14, 4.8.15, 4.8.16, 4.8.17, 4.8.18, 4.8.19, 4.8.2, 4.8.20, 4.8.21, 4.8.22, 4.8.23, 4.8.24, 4.8.25, 4.8.26, 4.8.27, 4.8.28, 4.8.29, 4.8.3, 4.8.30, 4.8.31, 4.8.32, 4.8.33, 4.8.34, 4.8.4, 4.8.5, 4.8.6, 4.8.7, 4.8.8, 4.8.9, 4.8.x-dev].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by jansenfelipe** [comment]
Boa noite @tloriato ! Bom, vc está quase lá rs.. Esse erro aparece quando vc não tem determinadas extensões do PHP instaladas na máquina.

Para isso, vc precisa interpretar a mensagem e tomar as devidas ações :smile: 

Vou te ajudar! Dê uma lida na mensagem que aparece:

> phpunit/phpunit 4.8.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.

Resumindo, ela diz que é necessário a extensão dom do PHP estar instalada. Veja se esta resposta no Stackoverflow ajuda vc http://stackoverflow.com/a/38285064

Um abraço!

**Comment by tloriato** [comment]
@jansenfelipe Obrigado pela atenção! Consegui resolver aquele problema específico, mas outro já surgiu. 
```
tloriato@tloriato-desktop:~/Documents/cpf-gratis$ php -S localhost:8000 -t example
PHP 7.0.13-0ubuntu0.16.04.1 Development Server started at Sun Feb  5 13:19:07 2017
Listening on http://localhost:8000
Document root is /home/tloriato/Documents/cpf-gratis/example
Press Ctrl-C to quit.
[Sun Feb  5 13:19:18 2017] PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' in /home/tloriato/Documents/cpf-gratis/src/CpfGratis.php on line 23
[Sun Feb  5 13:19:18 2017] PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYHOST - assumed 'CURLOPT_SSL_VERIFYHOST' in /home/tloriato/Documents/cpf-gratis/src/CpfGratis.php on line 24
[Sun Feb  5 13:19:18 2017] PHP Notice:  Use of undefined constant CURLOPT_SSLVERSION - assumed 'CURLOPT_SSLVERSION' in /home/tloriato/Documents/cpf-gratis/src/CpfGratis.php on line 25
[Sun Feb  5 13:19:18 2017] PHP Fatal error:  Uncaught GuzzleHttp\Ring\Exception\RingException: Error creating resource: [message] fopen(): Failed to enable crypto
[file] /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 406
[message] fopen(https://www.receita.fazenda.gov.br/Aplicacoes/SSL/ATCTA/CPF/ConsultaPublica.asp): failed to open stream: operation failed
[file] /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 406
[message] Undefined variable: http_response_header
[file] /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 407 in /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php:177
Stack trace:
#0 /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php(409): GuzzleHttp\Ring\Client\StreamHandler->createResource(Object(Closure), Array, Array)
#1 /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php(2 in /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 51
[Sun Feb  5 13:19:18 2017] 127.0.0.1:56180 [500]: / - Uncaught GuzzleHttp\Ring\Exception\RingException: Error creating resource: [message] fopen(): Failed to enable crypto
[file] /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 406
[message] fopen(https://www.receita.fazenda.gov.br/Aplicacoes/SSL/ATCTA/CPF/ConsultaPublica.asp): failed to open stream: operation failed
[file] /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 406
[message] Undefined variable: http_response_header
[file] /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 407 in /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php:177
Stack trace:
#0 /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php(409): GuzzleHttp\Ring\Client\StreamHandler->createResource(Object(Closure), Array, Array)
#1 /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php(2 in /home/tloriato/Documents/cpf-gratis/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 51

```

:(

**Comment by jansenfelipe** [comment]
@tloriato a extensão SSL está habilitada no seu PHP? Execute o comando abaixo para verificar:

`php -i | grep -i openssl`

![image](https://cloud.githubusercontent.com/assets/3134214/22631031/a98a94f8-ebec-11e6-999b-b7a6a2df6907.png)

**Comment by tloriato** [comment]
Está sim, @jansenfelipe !
```
tloriato@tloriato-desktop:~$ php -i | grep -i openssl
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.2g  1 Mar 2016
OpenSSL Header Version => OpenSSL 1.0.2g  1 Mar 2016
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
Native OpenSSL support => enabled

```

Que saudades do node... hahah
