### ISSUE TITLE
Erro no guzzlehttp 

### ISSUE THREAD

**Issue by ghost** [jansenfelipe/cpf-gratis#25]
Erro ao tentar usar essa lib

Fatal error: Uncaught GuzzleHttp\Ring\Exception\ConnectException: cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.receita.fazenda.gov.br:443 in C:\xampp\htdocs\cpf3\vendor\guzzlehttp\ringphp\src\Client\CurlFactory.php:126 Stack trace: #0 C:\xampp\htdocs\cpf3\vendor\guzzlehttp\ringphp\src\Client\CurlFactory.php(91): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Array, Array, Array) #1 C:\xampp\htdocs\cpf3\vendor\guzzlehttp\ringphp\src\Client\CurlHandler.php(96): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Array, Array, Array, Array, Resource id #86) #2 C:\xampp\htdocs\cpf3\vendor\guzzlehttp\ringphp\src\Client\CurlHandler.php(68): GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray(Array) #3 C:\xampp\htdocs\cpf3\vendor\guzzlehttp\ringphp\src\Client\Middleware.php(54): GuzzleHttp\Ring\Client\CurlHandler->__invoke(Array) #4 C:\xampp\htdocs\cpf3\vendor\guzzlehttp\ringphp\src\Client\Middleware.php(30): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array) #5 C:\xa in C:\xampp\htdocs\cpf3\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 49

**Comment by tgbaldo** [comment]
Estou tendo o mesmo problema
